version: "3"
services:
  reverse-proxy:
    build:
      context: .
    image: reverse-proxy
    container_name: reverse-proxy
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - "aee_tech_front"
      - "aee_digital_regionais"
      - "aee_digital_trabalhos"
    tty: true
  aee_digital_regionais:
    command: npm start
    # image: docker.pkg.github.com/brunoduartec/aee_digital_regionais/aee_digital_regionais
    image: aee_digital_regionais:latest
    container_name: aee_digital_regionais
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - app-network
    depends_on:
      - "db"
    tty: true
  aee_digital_trabalhos:
    command: npm start
    # image: docker.pkg.github.com/brunoduartec/aee_digital_trabalhos/aee_digital_trabalhos
    image: aee_digital_trabalhos:latest
    container_name: aee_digital_trabalhos
    ports:
      - "3100:3100"
    volumes:
      - .:/usr/app
    networks:
      - app-network
    depends_on:
      - "db"
    tty: true
  aee_tech_front:
    # image: docker.pkg.github.com/brunoduartec/aee_tech_front/aeetechfront:latest
    image: aee_tech_front:latest
    container_name: aee_tech_front
    ports:
      - "4200:4200"
    depends_on:
      - aee_digital_regionais
    networks:
      - app-network
    tty: true
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
    restart: always
    ports:
      - 52000:3306
    expose:
      - 52000
    environment:
      MYSQL_ROOT_PASSWORD: aeepw
      MYSQL_DATABASE: aee
      MYSQL_USER: aee
      MYSQL_PASSWORD: aeepw
    networks:
      - app-network
    tty: true
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - app-network
    tty: true
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    tty: true

networks:
  app-network:
    driver: bridge
