version: "3"
services:
  aee_digital_trabalhos:
    command: npm start
    image: docker.pkg.github.com/brunoduartec/aee_digital_trabalhos/aee_digital_trabalhos
    # image: aee_digital_trabalhos:latest
    container_name: aee_digital_trabalhos
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - .:/usr/app
    networks:
      - app-network
    depends_on:
      - "db"
    tty: true
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
    restart: always
    ports:
      - 52000:3306
    expose:
      - 52000
    environment:
      MYSQL_ROOT_PASSWORD: aeepw
      MYSQL_DATABASE: aee
      MYSQL_USER: aee
      MYSQL_PASSWORD: aeepw
    networks:
      - app-network
    tty: true
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - app-network
    tty: true

networks:
  app-network:
    driver: bridge
