version: "3"
services:
  aee_digital_trabalhos:
    command: npm start
    image: docker.pkg.github.com/brunoduartec/aee_digital_trabalhos/aee_digital_trabalhos
    container_name: aee_digital_trabalhos
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - .:/usr/app
    networks:
      - app-network
    tty: true
networks:
  app-network:
    driver: bridge
