version: "3"
services:
  aee_digital_regionais:
    command: npm start
    image: docker.pkg.github.com/brunoduartec/aee_digital_regionais/aee_digital_regionais
    container_name: aee_digital_regionais
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - app-network
    tty: true
networks:
  app-network:
    driver: bridge
