version: "3"

services:
  regionais_db:
    image: mysql:5.7
    container_name: regionais_db
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
    restart: always
    ports:
      - 52000:3306
    expose:
      - 52000
    environment:
      MYSQL_ROOT_PASSWORD: aeepw
      MYSQL_DATABASE: aee
      MYSQL_USER: aee
      MYSQL_PASSWORD: aeepw
    networks:
      - app-network
  aee_digital_regionais:
    command: npm start
    image: docker.pkg.github.com/brunoduartec/aee_digital_regionais/aee_digital_regionais
    # image: aee_digital_regionais:latest
    container_name: aee_digital_regionais
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - app-network
    depends_on:
      - "regionais_db"
networks:
  app-network:
    driver: bridge
