version: "3"
services:
  aee_digital_front:
    image: docker.pkg.github.com/brunoduartec/aee_digital_front/aee_digital_front:latest
    # image: aee_digital_front:latest
    container_name: aee_digital_front
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - aee_digital_regionais
    networks:
      - app-network
    tty: true
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./.mysql-data/db:/var/lib/mysql
    restart: always
    ports:
      - 52000:3306
    expose:
      - 52000
    environment:
      MYSQL_ROOT_PASSWORD: aeepw
      MYSQL_DATABASE: aee
      MYSQL_USER: aee
      MYSQL_PASSWORD: aeepw
    networks:
      - app-network
    tty: true
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - app-network
    tty: true

networks:
  app-network:
    driver: bridge
