version: "3"
services:
  aee_digital_front:
    image: docker.pkg.github.com/brunoduartec/aee_digital_front/aee_digital_front:latest
    container_name: aee_digital_front
    restart: always
    ports:
      - "4200:4200"
    networks:
      - app-network
    tty: true
networks:
  app-network:
    driver: bridge
